# services:
#   db:
#     image: mysql
#     container_name: soundme
#     restart: always
#     ports:
#       - 3308:3306
#     environment:
#       MYSQL_DATABASE: "soundme"
#       MYSQL_USER: "soundme"
#       MYSQL_PASSWORD: "soundme"
#       MYSQL_ROOT_PASSWORD: "root"
#     expose:
#       - 3308
#     volumes:
#       - ./db_data:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

version: "3.9"

services:
  db:
    image: mysql
    container_name: soundme-db
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: "soundme"
      MYSQL_USER: "soundme"
      MYSQL_PASSWORD: "soundme"
      MYSQL_ROOT_PASSWORD: "root"
    expose:
      - 3308
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Back
    container_name: soundme-backend
    ports:
      - 8888:8888
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: "soundme"
      DB_PASSWORD: "soundme"
      DB_NAME: "soundme"
      JWT_SECRET: ${JWT_SECRET}
      JWT_TIMING: 1h
      UPLOADS_FOLDER: ${UPLOADS_FOLDER}
    depends_on:
      - db
