services:
  db:
    image: mysql
    container_name: soundme
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: "soundme"
      MYSQL_USER: "soundme"
      MYSQL_PASSWORD: "soundme"
      MYSQL_ROOT_PASSWORD: "root"
    expose:
      - 3308
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
   

   soundme-back:
    build: .
    container_name: soundme-back
    image: soundme
    depends_on:
     - db
    ports:
      - 8888:8888
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: soundme
      DB_PASSWORD: soundme
    links: 
     - db  
    